services:
  # Web service
  - type: web
    name: the-homies-chat
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NEXTAUTH_URL
        fromService:
          name: the-homies-chat
          type: web
          property: url
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: the-homies-db
          property: connectionString

databases:
  - name: the-homies-db
    plan: free
    ipAllowList: []
